spring:
  datasource:
    url: jdbc:mysql://111.230.145.130:3217/geek_dev
    username: geek
    password: Geek.319
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database: MYSQL
      show-sql: true
      hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  activemq:
    broker-url:
  session:
    store-type: redis
  redis:
    host: www.kgeek.cn
    password: geek.007
    port: 6377
server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8

com.guazi:
  baseUrl: www.guazi.com
  group: sale

application:
  name: demo